on:
  push:
    branches: 
      - main

name: Build & Release

jobs:
  build:
    name: Build repo
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.16'
      - run: yarn install --frozen-lockfile
      - run: yarn build